ALTER TABLE `pastes` CHANGE `ts` `create_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `pastes` ADD `last_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- increase character limit to 48
ALTER TABLE pastes MODIFY title VARCHAR(48) NOT NULL DEFAULT '';


